name: Microsoft Security DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write   # required for GitHub code scanning alerts

jobs:
  msdo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1
        with:
          categories: 'code,artifacts,containers,secrets'

